spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
app:
  admin_token: "user-token"
  admin_password: "secretadmin123"